run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: relay/go # Replace with actual module path

linters:
  enable:
    - gofmt
    - goimports
    - revive
    - staticcheck
    - unparam
    - unused
    - errcheck
    - gosimple
    - ineffassign
    - typecheck