name: E2E Browser Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
        working-directory: e2e
      - name: Install browsers
        run: npx playwright install --with-deps
        working-directory: e2e
      - name: Run Playwright tests (public)
        run: npx playwright test tests/reddit_modqueue_smoke.spec.ts
        working-directory: e2e
      - name: Run Playwright tests (authenticated)
        if: ${{ secrets.E2E_STORAGE_STATE_JSON != '' }}
        env:
          E2E_STORAGE_STATE_JSON: ${{ secrets.E2E_STORAGE_STATE_JSON }}
          STORAGE_STATE: storage-state.json
        run: |
          echo "$E2E_STORAGE_STATE_JSON" > storage-state.json
          npx playwright test tests/reddit_modqueue_authenticated.spec.ts
        working-directory: e2e

