name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32'
      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze code
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Enforce coverage threshold
        run: |
          pct=$(lcov --summary coverage/lcov.info | awk '/lines/ {print $2}' | sed 's/%//')
          echo "Coverage: ${pct}%"
          awk -v p="$pct" 'BEGIN { if (p+0 < 75) { print "Coverage below 75%: " p "%"; exit 1 } }'

