name: Go Relay CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
      - name: Tidy and build
        run: |
          go mod tidy
          go build ./...
        working-directory: relay/go
      - name: Run tests
        run: go test -coverprofile=coverage.out ./...
      - name: Enforce coverage threshold
        run: |
          pct=$(go tool cover -func=coverage.out | awk '/total:/ {print $3}' | sed 's/%//')
          echo "Coverage: ${pct}%"
          awk -v p="$pct" 'BEGIN { if (p+0 < 75) { print "Coverage below 75%: " p "%"; exit 1 } }'
        working-directory: relay/go

