name: Go Relay CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
      - name: Tidy and build
        run: |
          go mod tidy
          go build ./...
        working-directory: relay/go
      - name: Run tests
        run: go test ./...
        working-directory: relay/go

